### ISSUE TITLE
Notification of server status

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/preprint-similarity-search#76]
Per #72 , it'd be nice to be notified (slack? email? github notif?) when the server/app isn't working, either because our server is down or bioRxiv's is.

**Comment by vincerubinetti** [comment]
This might actually be pretty easy with github actions.

```yaml
name: Check PSS server

on:
  # run every hour
  schedule:
    - cron: '0 * * * * '

jobs:
  test-pss:
    runs-on: ubuntu-latest
    steps:
      - name: Check default preprint
        run: `curl https://api-pss.greenelab.com/doi/10.1101/833400`
      - name: Create issue if error
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
